// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeaa6LWON62gLku0tQ8NZeinEMgqsXQzA',
    appId: '1:195070662504:web:56a59c3b083c5b9f74a8dd',
    messagingSenderId: '195070662504',
    projectId: 'sporty-12bce',
    authDomain: 'sporty-12bce.firebaseapp.com',
    storageBucket: 'sporty-12bce.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAapZ_AmGPUMv9LtrJEQPv589Yw5lKUh0M',
    appId: '1:195070662504:android:a427722d9efbf6f774a8dd',
    messagingSenderId: '195070662504',
    projectId: 'sporty-12bce',
    storageBucket: 'sporty-12bce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTF96TfIgUBPis16TWwvtYYUNkkRrqgP4',
    appId: '1:195070662504:ios:7f19a44d20f9eef074a8dd',
    messagingSenderId: '195070662504',
    projectId: 'sporty-12bce',
    storageBucket: 'sporty-12bce.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTF96TfIgUBPis16TWwvtYYUNkkRrqgP4',
    appId: '1:195070662504:ios:7f19a44d20f9eef074a8dd',
    messagingSenderId: '195070662504',
    projectId: 'sporty-12bce',
    storageBucket: 'sporty-12bce.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCeaa6LWON62gLku0tQ8NZeinEMgqsXQzA',
    appId: '1:195070662504:web:a9faf0ae8c887d9274a8dd',
    messagingSenderId: '195070662504',
    projectId: 'sporty-12bce',
    authDomain: 'sporty-12bce.firebaseapp.com',
    storageBucket: 'sporty-12bce.appspot.com',
  );
}
