name: sporty_application
description: A new Flutter project.

publish_to: 'none'

version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  permission_handler: ^11.3.1
  google_maps_flutter: ^2.6.1
  google_maps_flutter_web: ^0.5.7
  geolocator: ^7.6.2
  flutter:
    sdk: flutter
  provider: ^6.0.0
  pedometer: ^4.0.0
  font_awesome_flutter: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.0.6

flutter:
  uses-material-design: true
  assets:
    - assets/background.png
    - assets/chita.png
    - assets/logo.png
    - assets/megafone.png
    - assets/paths.png
    - assets/medal.png
    - assets/flag.png
    - assets/button.png
    - assets/headphones.png
    - assets/cap.png
    - assets/glasses.png
    - assets/watch.png
    - assets/helmet.png
    - assets/sunglasses.png
    - assets/hat.png
    - assets/Workouts_Assests/caminhada.png
    - assets/Workouts_Assests/corrida.png
    - assets/Workouts_Assests/cycling.png
    - assets/Workouts_Assests/gym.png
    - assets/Workouts_Assests/desportos.png
    - assets/Workouts_Assests/basketball.png
    - assets/Workouts_Assests/free_training.png
    - assets/chitaCap.png
    - assets/chitaG.png
    - assets/chitaG2.png
    - assets/chitaH.png
    - assets/chitaHel.png
    - assets/chitaW.png

flutter_native_splash:
  color: "#42a5f5"
  image: assets/logo.png
  android: true
  fullscreen: true
